### ISSUE TITLE
Saumya (Review Ticket Week 0)

### ISSUE THREAD

**Issue by saumyapalk23** [sarayu-pr11/saas#6]
- [ ] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

- [ ]  GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime

- [ ]  GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by rkaavya** [comment]
GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/)) (1/1)

 GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime (1.5/1)

 GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime (1/1)

Everything is up to date and working, and the Christmas tree code is there. Overall grade: 3.5/3
